name: Build WatchList Executable

on:
  push:
    paths:
      - '**.pyw'
      - '.github/workflows/build-executable.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6

      - name: Build executable
        run: |
          pyinstaller watchlist.pyw --name=WatchList --onefile --windowed

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: WatchList-${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'windows-latest' && 'windows' || 'macos') }}
          path: dist/WatchList*
